title: Naveen Sunder
description: Assistant Professor of Economics, Bentley University
layout: page
sidebar: true
  nav: 
    home: /
    tags: /tags.html
featured-tags: true
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
