title: Naveen Sunder
description: Assistant Professor of Economics, Bentley University
layout: page
sidebar: true
  nav: 
    home: /
    tags: /tags.html
featured-tags: true
logo: /assets/img/logo.png
show_downloads: true
nav:
    - Home: 'index.md'
    - Bio: 'Aboutme.md'
theme: jekyll-theme-minimal
