title: Naveen Sunder
description: Assistant Professor of Economics, Bentley University
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
show_downloads: false
logo: content/gr.jpg
theme: jekyll-theme-minimal
