relativeURLs = true
title = "Naveen Sunder"
theme = "jekyll-theme-minimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Assistant Professor of Economics, Bentley University"
    logo = "gr.jpg" 
